### PR TITLE
Added subscreens to periodic table face; added title and faster scrol…

### PR DESCRIPTION
**Pull request by voloved**
## Additions

* Added Electronegativity, Date Discovered, and Full Name (Screens changed by pressing MODE btn)
* Changed scrolling to be done by holding the forward or back keys
* Added a title screen
* Atomic Mass now includes decimal points.

## Demo
https://github.com/user-attachments/assets/508583ba-95a1-40f5-8a2b-ca96118f2bed
* Hydrogen discovery date shows 23BC, which is incorrect, but only used for the demo to show a BC date. Array has the discovery date as 1671

## Navigation
* Mode Press
  * On Title: Next Screen
  * Else: Cycle through info of an element
 
* Mode Hold
  * On Title: First Screen
  * On Element Symbol Screen: Go to Title Screen
  * Else: Go to Symbol Screen of current element
  * If you are in a subscreen and just keep holding MODE, you will go through all of these menus without needing to depress.

* Light Press
  * Previous Element

* Light Hold
  * Fast Cycle through Previous Elements

* Alarm Press
  * Next Element

* Alarm Hold
  * Fast Cycle through Next Elements

## Sources
* https://en.wikipedia.org/wiki/List_of_chemical_elements
* https://en.wikipedia.org/wiki/Discovery_of_chemical_elements

### CODE REVIEW

**Comment by PrimmR** [comment]
Wow, this is great! It certainly makes the face a whole lot more useful and usable than before.

I've not seen the use of a mode button for anything other than switching faces, but I think your implementation does a very good job at staying intuitive, while still freeing up the extra button.

My only request is that it would be great if you could add a short description and instructions on how to use the updated face in the header file - I did put a sentence of instruction in there, but admittedly it probably wasn't enough even for the old face. (If you don't want to do it, I can do it myself, but I'll probably end up missing something important)

I see you might still be ironing out some bugs and features? So just tell me when you think it's good to be merged! Hopefully these changes might get this face one step closer to being included in the main set of movement faces. And also thank you so much for being the first contributor, it really means a lot!!

**Comment by voloved** [comment]
> Wow, this is great! It certainly makes the face a whole lot more useful and usable than before.
> 
> I've not seen the use of a mode button for anything other than switching faces, but I think your implementation does a very good job at staying intuitive, while still freeing up the extra button.
> 
> My only request is that it would be great if you could add a short description and instructions on how to use the updated face in the header file - I did put a sentence of instruction in there, but admittedly it probably wasn't enough even for the old face. (If you don't want to do it, I can do it myself, but I'll probably end up missing something important)
> 
> I see you might still be ironing out some bugs and features? So just tell me when you think it's good to be merged! Hopefully these changes might get this face one step closer to being included in the main set of movement faces. And also thank you so much for being the first contributor, it really means a lot!!

Thanks! I added documentation. It should be good now :)

**Comment by PrimmR** [comment]
Great! Thanks so much

Oh, and shall I also add you to the authors in the copyright notice? If so what name would you like to be attributed as?

**Comment by voloved** [comment]
> Great! Thanks so much
> 
> Oh, and shall I also add you to the authors in the copyright notice? If so what name would you like to be attributed as?

Sure! David Volovskiy is my name.

**Pull request merged**
